baseurl = "//tobybase.com"
title = "👨🏻‍💻 Tobybase"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "tobybase-com"

enableEmoji = true

[params]
    author = "Toby Marks"
    info = "Principal Consultant at Infolob"
    description = "My tech blog"
    keywords = "oracle,infolob,blog,consultant,developer,tuning,exadata,personal"
    avatarurl = "/img/toby.png"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = "Oracle Database Developer and Performance Tuner, specialized on the Exadata platform. Working for Infolob from Irving, Texas."
    hidecredits = true
    hidecopyright = false
    since = 2012

    rtl = false   

	# Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
#    colorscheme = "light"
    
	math = false
    custom_css = ["css/custom.css"]
#     custom_js = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
# [params.fathomAnalytics]
#     siteID = ""
#     # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
#     serverURL = ""

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/toby-marks/"
# [[params.social]]
#     name = "Gitlab"
#     icon = "fab fa-gitlab fa-2x"
#     weight = 2
#     url = "https://gitlab.com/johndoe/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 2
    url = "https://www.linkedin.com/in/tobymarks/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/toby_marks/"
# [[params.social]]
#     name = "Facebook"
#     icon = "fab fa-facebook fa-2x"
#     weight = 4
#     url = "https://facebook.com/tobyjmarks/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "Links"
    weight = 2
    url  = "/links/"
[[menu.main]]
    name = "About"
    weight = 3
    url = "/about/"
    
# Taxonomies
[taxonomies]
	category = "categories"
	tag = "tags"
	series = "series"

