baseurl             = "http://tobybase.com"  # the baseurl for your website
title               = "Tobybase: A Tech Blog"             # blog title
paginate            = 10                     # the number of posts on a page
publishDir          = "docs"
theme               = "hugo-multi-bootswatch"
disqusShortname     = "tobybase-com"

# insert color codes directly into page. used for server-side syntax highlighting with pygments.
pygmentsuseclasses = false
pygmentsstyle = "autumn"
PygmentsCodeFences = true

[permalinks]
    # Optional. Change the permalink format for the 'post' content type.
    # The format shown here is the same one Jekyll/Octopress uses by default.
    post = "/blog/:year/:month/:day/:title/"

[author]
    # Optional. Used in RSS feed meta information.
    name = "Toby Marks"
    email = "toby.marks@infolob.com"

[params]
    # language code for your website
    languagecode = "en-US"

    # name of the site author; used in header meta information
    author = "Toby Marks"

    # copyright text; used in footer
    copyright = "2017 ~ Toby Marks"

    # social links, used in footer, these must be full URLs.
    twitter     = "https://twitter.com/toby_marks"
    github      = "https://github.com/toby-marks"
#    facebook    = "https://www.facebook.com/<username>"
#    delicious   = "https://delicious.com/<username>"
    linkedin    = "https://www.linkedin.com/in/tobymarks"
#    flickr      = "https://www.flickr.com/photos/<username>"

    # show default summaries on the frontpage or not
    use_summaries = true

# naming of the elements in your blog/site
[params.strings]
    # name of the link to the homepage
    home_navbar_link = "Home"

    # name of the link to the blog page
    blog_navbar_link = "Blog"

    # name of the header used in the post list page
    posts_list_header = "Posts"

    # used date format
    date_format = '01/02/2006'

[params.theme]
    inverse = false     # indicating if the theme should use inversed colors
    name = "united"   # name of the theme to use

    # list of possible theme names that can be used
    # name = "cerulean"
    # name = "cosmo"
    # name = "cyborg"
    # name = "default"
    # name = "flatly"
    # name = "journal"
    # name = "lumen"
    # name = "paper"
    # name = "readable"
    # name = "sandstone"
    # name = "simplex"
    # name = "slate"
    # name = "spacelabs"
    # name = "superhero"
    # name = "united"
    # name = "yeti"
