[build]
publish = "public"
command = "hugo --themesDir=../.. --baseURL $URL"

[build.environment]
HUGO_VERSION = "0.147.7+extended+withdeploy"
HUGO_THEME = "coder"

[context.deploy-preview]
command = "hugo --themesDir=../.. --buildFuture --buildDrafts --baseURL $DEPLOY_PRIME_URL"
